# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stakater-be-app
spec:
  selector:
      matchLabels:
        app: stakater-be-app
        tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: stakater-be-app
        tier: backend
    spec:
      containers:    
        - name: stakater-be-app
          image: sardarwaqasahmed/stakater-be:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
          env:
          - name: NAME_PREFIX
            value: "Waqas-Ahmed"
---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: stakater-be-service
spec:
  selector:
    app: stakater-be-app
    tier: backend
  ports:
  - protocol: TCP
    port: 8081    
  type: ClusterIP
