apiVersion: apps/v1
kind: Deployment
metadata:
  name: stakater-be-api
spec:
  selector:
      matchLabels:
        app: stakater-be-api
        tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: stakater-be-api
        tier: backend
    spec:
      containers:    
        - name: stakater-be-api
          image: sardarwaqasahmed/stakater-be:latest
          env:
          - name: name.prefix
            value: "Waqas-Ahmed"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081